#!/bin/sh

# This will be moved into the .git/hooks repository by ./format.sh the first time you run it.

find app -iname '*.h*' -o -iname '*.cpp' | xargs clang-format -Werror --dry-run
exit_code_1=$?

find netlib -iname '*.h*' -o -iname '*.cpp' | xargs clang-format -Werror --dry-run
exit_code_2=$?

if [[ $exit_code_1 -ne 0 || $exit_code_2 -ne 0 ]]; then
  echo "Formatting check failed. Please run \"format.sh\", re-add the files, and try again."
  exit 1
fi

echo "Formatting check succeeded."
exit 0

