#pragma once

// Autogenerated by the ui file. If this isn't found by your IDE, build the
// project first.
#include "ui_mainwindow.h"

#include <QMainWindow>

class MainWindow : public QMainWindow
{
  // This "enables" this class to be run through Qt's Meta compiler, which
  // will add extra hidden fields and features. All Qt classes need it.
  Q_OBJECT;

public:
  MainWindow(QWidget *parent = nullptr);

private slots:
  void on_settingsButton_clicked();

private:
  // This is an instance of the C++ class autogenerated from
  // the mainwindow.ui file upon compilation. To edit the ui generated,
  // open mainwindow.ui in Qt Creator and enter the design tab. Note that
  // using a ui file is completely optional.
  Ui_MainWindow ui;
};
