# .github/workflows/jekyll.yml
name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Match your local Ruby version

    - name: Install dependencies
      working-directory: docs
      run: |
        gem install bundler
        bundle install

    - name: Build site with Jekyll
      working-directory: docs
      run: bundle exec jekyll build --destination ./docs/_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
